module.exports = {
  extends: 'eslint:recommended',
  rules: {
    'accessor-pairs': ['error', {
      setWithoutGet: true,
    }],
    'array-bracket-spacing': ['error', 'never'],
    'array-callback-return': ['error'],
    'block-scoped-var': 'error',
    'brace-style': ['error', 'stroustrup'],
    'camelcase': ['error'],
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['error', {
      after: true,
      before: false,
    }],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': 'error',
    'curly': 'error',
    'eol-last': 'error',
    'eqeqeq': ['error', 'smart'],
    'func-call-spacing': ['error', 'never'],
    'func-style': ['error', 'declaration'],
    'function-call-argument-newline': ['error', 'consistent'],
    'function-paren-newline': ['error', 'consistent'],
    'implicit-arrow-linebreak': ['error', 'beside'],
    'indent': ['error', 2, {
      MemberExpression: 0,
    }],
    'key-spacing': ['error', {
      afterColon: true,
      beforeColon: false,
      mode: 'strict',
    }],
    'keyword-spacing': ['error', {
      after: true,
      before: true,
    }],
    'line-comment-position': ['error', 'above'],
    'max-depth': ['warn', 5],
    'max-len': 'off',
    'max-statements': ['warn', 40],
    'new-cap': 'warn',
    'new-parens': ['error', 'always'],
    'newline-per-chained-call': ['error', {
      ignoreChainWithDepth: 2,
    }],
    'no-extend-native': 'error',
    'no-extra-parens': ['error', 'all', {
      enforceForArrowConditionals: true,
      ignoreJSX: 'multi-line',
      nestedBinaryExpressions: false,
    }],
    'no-inline-comments': 'error',
    'no-lonely-if': 'error',
    'no-loose-of-precision': 'error',
    'no-mixed-operators': ['error', {
      allowSamePrecedence: true,
    }],
    'no-mixed-spaces-and-tabs': 'error',
    'no-multiple-empty-lines': ['error', {
      max: 1,
    }],
    'no-nested-ternary': 'error',
    'no-promise-executor-return': 'error',
    'no-return-assign': 'error',
    'no-shadow': 'warn',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-undef': 'error',
    'no-undefined': 'error',
    'no-underscore-dangle': ['error', {
      allowAfterSuper: true,
      allowAfterThis: true,
    }],
    'no-unreachable-loop': 'error',
    'no-unused-vars': ['warn', {
      args: 'after-used',
      argsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      vars: 'all',
    }],
    'no-use-before-define': 'off',
    'object-curly-spacing': ['error', 'never'],
    'one-var': ['error', 'never'],
    'padded-blocks': ['error', 'never'],
    'prefer-promise-reject-errors': 'error',
    'quotes': ['error', 'single', 'avoid-escape'],
    'require-atomic-updates': 'warn',
    'semi': ['error', 'never'],
    'space-before-function-paren': ['error', 'never'],
    'space-unary-ops': ['off', {
      nonwords: false,
      words: true,
    }],
    'valid-jsdoc': 'warn',
  },
}
